# Generated by Django 5.2.13 on 2026-04-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CtEntidadFinanciera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_identificador', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'ct_entidad_financiera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtEstadoOrden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_orden', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ct_estado_orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtEstadoVehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ct_estado_vehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtEstadoVenezuela',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ct_estado_venezuela',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtPais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_iso', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('continente', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ct_pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtTipoModelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ct_tipo_modelo',
                'managed': False,
            },
        ),
    ]
