# Generated by Django 5.2.13 on 2026-04-22 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=255)),
                ('cliente_email', models.EmailField(max_length=254)),
                ('cliente_telefono', models.CharField(max_length=20)),
                ('referencia', models.CharField(max_length=100, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('modelo_vehiculo', models.CharField(max_length=100)),
                ('year_vehiculo', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(max_length=50)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True, default='')),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(db_column='vendedor_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orden_venta',
                'ordering': ['-created_at'],
            },
        ),
    ]
