# Generated by Django 6.0.4 on 2026-05-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtEstadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_pago', models.CharField(db_column='estado_pago', max_length=100)),
            ],
            options={
                'verbose_name': 'Estado de Pago',
                'verbose_name_plural': 'Estados de Pagos',
                'db_table': 'ct_estado_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtEstadoReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_reclamo', models.CharField(db_column='estado_reclamo', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Estado de Reclamo',
                'verbose_name_plural': 'Estados de Reclamos',
                'db_table': 'ct_estado_reclamo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtMetodoPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ct_metodo_pago',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='ctentidadfinanciera',
            options={'managed': False, 'verbose_name': 'Entidad Financiera', 'verbose_name_plural': 'Entidades Financieras'},
        ),
        migrations.AlterModelOptions(
            name='ctestadoorden',
            options={'managed': False, 'verbose_name': 'Estado de Orden', 'verbose_name_plural': 'Estados de Órdenes'},
        ),
        migrations.AlterModelOptions(
            name='ctestadovehiculo',
            options={'managed': False, 'verbose_name': 'Estado de Vehículo', 'verbose_name_plural': 'Estados de Vehículos'},
        ),
        migrations.AlterModelOptions(
            name='ctestadovenezuela',
            options={'managed': False, 'verbose_name': 'Estado de Venezuela', 'verbose_name_plural': 'Estados de Venezuela'},
        ),
        migrations.AlterModelOptions(
            name='ctpais',
            options={'managed': False, 'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='cttipomodelo',
            options={'managed': False, 'verbose_name': 'Tipo de Modelo', 'verbose_name_plural': 'Tipos de Modelos'},
        ),
    ]
