# Generated by Django 6.0.4 on 2026-05-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstadosOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, db_column='fecha_cambio')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Orden',
                'verbose_name_plural': 'Historial de Estados de Órdenes',
                'db_table': 'historial_estados_orden',
                'ordering': ['-fecha_cambio'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediaAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla_referencia', models.CharField(db_column='tabla_referencia', max_length=100)),
                ('registro_id', models.BigIntegerField(db_column='registro_id')),
                ('tipo_archivo', models.CharField(db_column='tipo_archivo', max_length=50, null=True)),
                ('url_archivo', models.TextField(db_column='url_archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, db_column='fecha_subida')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
                'db_table': 'media_adjunto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vigencia', models.DateTimeField(db_column='fecha_vigencia', null=True)),
                ('fecha_vencimiento', models.DateTimeField(db_column='fecha_vencimiento', null=True)),
                ('kilometraje_garantia', models.CharField(db_column='kilometraje_garantia', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Registro de Garantía',
                'verbose_name_plural': 'Registros de Garantías',
                'db_table': 'registro_garantia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransaccionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(db_column='monto', decimal_places=2, max_digits=12, null=True)),
                ('monto_inicial', models.DecimalField(db_column='monto_inicial', decimal_places=2, max_digits=12, null=True)),
                ('monto_restante', models.DecimalField(db_column='monto_restante', decimal_places=2, max_digits=12, null=True)),
                ('moneda', models.CharField(db_column='moneda', max_length=10, null=True)),
                ('tasa_cambio', models.DecimalField(db_column='tasa_cambio', decimal_places=4, max_digits=10, null=True)),
                ('metodo_pago', models.IntegerField(db_column='metodo_pago', null=True)),
                ('referencia', models.CharField(db_column='referencia', max_length=100, unique=True)),
                ('fecha_pago', models.DateTimeField(db_column='fecha_pago', null=True)),
                ('verificado_por', models.IntegerField(db_column='verificado_por', null=True)),
            ],
            options={
                'verbose_name': 'Transacción de Pago',
                'verbose_name_plural': 'Transacciones de Pago',
                'db_table': 'transaccion_pago',
                'ordering': ['-fecha_pago'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='ordenventa',
            options={'managed': False, 'ordering': ['-fecha_creacion'], 'verbose_name': 'Orden de Venta', 'verbose_name_plural': 'Órdenes de Venta'},
        ),
    ]
