# Generated by Django 6.0.4 on 2026-05-07 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_ctestadopago_ctestadoreclamo_ctmetodopago_and_more'),
        ('sedes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CtEstadoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_column='codigo', max_length=30, unique=True)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('orden', models.IntegerField(db_column='orden', default=0)),
                ('color_hex', models.CharField(blank=True, db_column='color_hex', max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Estado de Lote',
                'verbose_name_plural': 'Estados de Lote',
                'db_table': 'ct_estado_lote',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='LoteImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(db_column='codigo_lote', max_length=50, unique=True)),
                ('proveedor', models.CharField(db_column='proveedor', max_length=200)),
                ('puerto_origen', models.CharField(db_column='puerto_origen', max_length=100)),
                ('puerto_destino', models.CharField(db_column='puerto_destino', max_length=100)),
                ('total_unidades', models.IntegerField(db_column='total_unidades')),
                ('fecha_orden_compra', models.DateField(blank=True, db_column='fecha_orden_compra', null=True)),
                ('fecha_embarque_estimado', models.DateField(blank=True, db_column='fecha_embarque_estimado', null=True)),
                ('fecha_embarque_real', models.DateField(blank=True, db_column='fecha_embarque_real', null=True)),
                ('fecha_llegada_estimada', models.DateField(blank=True, db_column='fecha_llegada_estimada', null=True)),
                ('fecha_llegada_real', models.DateField(blank=True, db_column='fecha_llegada_real', null=True)),
                ('numero_bl', models.CharField(blank=True, db_column='numero_bl', max_length=100, null=True)),
                ('numero_contenedores', models.IntegerField(blank=True, db_column='numero_contenedores', null=True)),
                ('agente_aduanal', models.CharField(blank=True, db_column='agente_aduanal', max_length=200, null=True)),
                ('valor_fob_usd', models.DecimalField(blank=True, db_column='valor_fob_usd', decimal_places=2, max_digits=15, null=True)),
                ('notas', models.TextField(blank=True, db_column='notas', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_creados', to=settings.AUTH_USER_MODEL)),
                ('estado_lote', models.ForeignKey(db_column='estado_lote_id', on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='lotes.ctestadolote')),
                ('pais_origen', models.ForeignKey(db_column='pais_origen_id', on_delete=django.db.models.deletion.PROTECT, related_name='lotes_importacion', to='catalogos.ctpais')),
                ('sede_destino', models.ForeignKey(db_column='sede_destino_id', on_delete=django.db.models.deletion.PROTECT, related_name='lotes_entrantes', to='sedes.sede')),
            ],
            options={
                'verbose_name': 'Lote de Importación',
                'verbose_name_plural': 'Lotes de Importación',
                'db_table': 'lote_importacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadosLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, db_column='fecha_cambio')),
                ('ubicacion', models.CharField(blank=True, db_column='ubicacion', max_length=255, null=True)),
                ('notas', models.TextField(blank=True, db_column='notas', null=True)),
                ('estado_anterior', models.ForeignKey(blank=True, db_column='estado_anterior_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_desde', to='lotes.ctestadolote')),
                ('estado_nuevo', models.ForeignKey(db_column='estado_nuevo_id', on_delete=django.db.models.deletion.PROTECT, related_name='historial_hacia', to='lotes.ctestadolote')),
                ('responsable', models.ForeignKey(blank=True, db_column='responsable_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_lote', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(db_column='lote_id', on_delete=django.db.models.deletion.PROTECT, related_name='historial_estados', to='lotes.loteimportacion')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Lote',
                'verbose_name_plural': 'Historial de Estados de Lotes',
                'db_table': 'historial_estados_lote',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
