# Generated by Django 5.2.13 on 2026-04-17 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_1', models.IntegerField(max_length=20)),
                ('telefono_2', models.IntegerField(max_length=20)),
                ('nacionalidad', models.IntegerField(max_length=50)),
                ('identificacion', models.IntegerField(max_length=50)),
                ('cargo', models.IntegerField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
