# Generated by Django 5.2.13 on 2026-04-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cargo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='identificacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nacionalidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono_2',
            field=models.IntegerField(),
        ),
    ]
