# Generated by Django 5.2.13 on 2026-04-17 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('pais_origen', models.ForeignKey(db_column='pais_origen', on_delete=django.db.models.deletion.PROTECT, to='catalogos.ctpais')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('marca', models.ForeignKey(db_column='marca_id', on_delete=django.db.models.deletion.CASCADE, to='vehiculos.marca')),
                ('tipo', models.ForeignKey(db_column='tipo', on_delete=django.db.models.deletion.PROTECT, to='catalogos.cttipomodelo')),
            ],
            options={
                'db_table': 'modelo',
            },
        ),
        migrations.CreateModel(
            name='VersionTrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_version', models.CharField(blank=True, max_length=255, null=True)),
                ('transmision', models.CharField(blank=True, max_length=100, null=True)),
                ('motorizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('año_modelo', models.DateField(blank=True, null=True)),
                ('modelo', models.ForeignKey(db_column='modelo_id', on_delete=django.db.models.deletion.CASCADE, to='vehiculos.modelo')),
            ],
            options={
                'db_table': 'version_trim',
            },
        ),
        migrations.CreateModel(
            name='VehiculoNuevo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_column='vin', max_length=255, unique=True)),
                ('numero_motor', models.CharField(max_length=255, unique=True)),
                ('numero_chasis', models.CharField(max_length=255, unique=True)),
                ('color_exterior', models.CharField(blank=True, max_length=100, null=True)),
                ('color_interior', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_llegada', models.DateTimeField(blank=True, null=True)),
                ('precio_lista_sugerido', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estado', models.ForeignKey(blank=True, db_column='estado', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.ctestadovehiculo')),
                ('ubicacion_fisica', models.ForeignKey(blank=True, db_column='ubicacion_estado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.ctestadovenezuela', verbose_name='Ubicación (Estado)')),
                ('version', models.ForeignKey(db_column='version_id', on_delete=django.db.models.deletion.PROTECT, to='vehiculos.versiontrim')),
            ],
            options={
                'db_table': 'vehiculo_nuevo',
            },
        ),
        migrations.CreateModel(
            name='EquipamientoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_caracteristica', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.ForeignKey(db_column='version_id', on_delete=django.db.models.deletion.CASCADE, related_name='equipamiento', to='vehiculos.versiontrim')),
            ],
            options={
                'db_table': 'equipamiento_base',
            },
        ),
    ]
