# Generated by Django 6.0.4 on 2026-05-07 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
        ('sedes', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamientobase',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='vehiculonuevo',
            options={'verbose_name': 'Vehículo Nuevo', 'verbose_name_plural': 'Vehículos Nuevos'},
        ),
        migrations.AddField(
            model_name='vehiculonuevo',
            name='lote',
            field=models.ForeignKey(blank=True, db_column='lote_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='lotes.loteimportacion'),
        ),
        migrations.AddField(
            model_name='vehiculonuevo',
            name='sede_actual',
            field=models.ForeignKey(blank=True, db_column='sede_actual_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='sedes.sede'),
        ),
        migrations.AlterField(
            model_name='vehiculonuevo',
            name='numero_chasis',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculonuevo',
            name='numero_motor',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
