# Generated by Django 6.0.4 on 2026-05-07 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_ctestadopago_ctestadoreclamo_ctmetodopago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sede', models.CharField(db_column='codigo_sede', max_length=20, unique=True)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('ciudad', models.CharField(db_column='ciudad', max_length=100)),
                ('direccion', models.CharField(db_column='direccion', max_length=255)),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=100, null=True)),
                ('activa', models.BooleanField(db_column='activa', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('encargado', models.ForeignKey(blank=True, db_column='encargado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sedes_a_cargo', to=settings.AUTH_USER_MODEL)),
                ('estado_venezuela', models.ForeignKey(blank=True, db_column='estado_venezuela_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sedes', to='catalogos.ctestadovenezuela')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'db_table': 'sede',
                'ordering': ['nombre'],
            },
        ),
    ]
