# Generated by Django 6.0.4 on 2026-05-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False, 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
