# Generated by Django 6.0.4 on 2026-05-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.IntegerField(db_column='nacionalidad', null=True)),
                ('identificacion', models.CharField(db_column='identificacion', max_length=50, unique=True)),
                ('telefono_1', models.CharField(blank=True, db_column='telefono_1', max_length=20, null=True)),
                ('telefono_2', models.CharField(blank=True, db_column='telefono_2', max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, db_column='direccion', max_length=255, null=True)),
                ('cargo', models.IntegerField(db_column='cargo', null=True)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'vendedor',
                'managed': False,
            },
        ),
    ]
